/*
 EQUIPO NUMERO 3
    ADRIAN PEREIRA
    MAURICIO RODRIGUEZ
    ALONDRA LEON
    ANDREA VALECILLOS
    WILLIANNY CHUELLO
 */
package vista;

import controlador.CtrlUsuario;
import controlador.CtrlBiblioteca;
import controlador.CtrlEjemplar;
import controlador.CtrlInicioSesion;
import controlador.CtrlPrestamo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import modelo.Biblioteca;
import modelo.Conexion;
import modelo.CrudBiblioteca;
import modelo.CrudEjemplar;
import modelo.CrudPrestamo;
import modelo.CrudUsuario;
import modelo.Ejemplar;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author HP
 */
public class Vista_gestionLibros extends javax.swing.JFrame {

    /**
     * Creates new form Vista_gestionLibros
     */
    public Vista_gestionLibros() {
        initComponents();
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        Connection con = conn.getConexion();
        
        try{
            String sql = "SELECT * FROM \"Categoria\"";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            combxCategLib.addItem("Seleccione Categoria");
            while(rs.next())
            {
                combxCategLib.addItem(rs.getString("nomCategoria"));
            
            }
            
            rs.close();
         
        }catch(SQLException e)
        {
            System.err.println(e.toString());
        }
        
        try{
            String sql = "SELECT * FROM \"Biblioteca\"";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            combxBiblioLib.addItem("Seleccione Biblioteca");
            while(rs.next())
            {
                combxBiblioLib.addItem(rs.getString("nomBiblioteca"));
            
            }
            
            rs.close();
         
        }catch(SQLException e)
        {
            System.err.println(e.toString());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        imgLogoLib = new javax.swing.JLabel();
        logoBiblioLib = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        pnlPrestamoLib = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblPrestamoLib = new javax.swing.JLabel();
        pnlEjemplarLib = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblEjemplarLib = new javax.swing.JLabel();
        pnlLibrosLib = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblLibrosLib = new javax.swing.JLabel();
        btn_biblio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblBiblioLib = new javax.swing.JLabel();
        pnlUsuarioLib = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        pnlPrincipalLib = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPrincipalLib = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JLabel();
        PanelSup = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        lblIdLibroLib = new javax.swing.JLabel();
        txtIdLibroLib = new javax.swing.JTextField();
        txtTituloLib = new javax.swing.JTextField();
        lblTituloLIb = new javax.swing.JLabel();
        txtAutorLib = new javax.swing.JTextField();
        lblAutorLib = new javax.swing.JLabel();
        txtAnnoLib = new javax.swing.JTextField();
        lblAnnoLib = new javax.swing.JLabel();
        txtCategLibros = new javax.swing.JTextField();
        lblCategoriaLib = new javax.swing.JLabel();
        btnBuscarLib = new javax.swing.JButton();
        btnModificarLib = new javax.swing.JButton();
        btnEliminarLib = new javax.swing.JButton();
        btnLimpiarLib = new javax.swing.JButton();
        combxCategLib = new javax.swing.JComboBox<>();
        btnRegistrarLib = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLibrosLib = new javax.swing.JTable();
        txtBiblioLib = new javax.swing.JTextField();
        combxBiblioLib = new javax.swing.JComboBox<>();
        lblIdBiblioLib = new javax.swing.JLabel();
        lblCantidadLib = new javax.swing.JLabel();
        txtCantidadLib = new javax.swing.JTextField();
        lblLibros1 = new javax.swing.JLabel();
        btnBuscarCantEj = new javax.swing.JButton();
        lblMostrarRegisLib = new javax.swing.JLabel();
        btnBuscarRegisLib = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(imgLogoLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 100));

        logoBiblioLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        logoBiblioLib.setForeground(new java.awt.Color(0, 204, 204));
        logoBiblioLib.setText("Bibliotecas");
        jPanel1.add(logoBiblioLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 40));

        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        pnlPrestamoLib.setBackground(new java.awt.Color(13, 104, 116));
        pnlPrestamoLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPrestamoLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPrestamoLibMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrestamoLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrestamoLibMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroPrestamo.png"))); // NOI18N

        lblPrestamoLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrestamoLib.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestamoLib.setText("Prestamo");

        javax.swing.GroupLayout pnlPrestamoLibLayout = new javax.swing.GroupLayout(pnlPrestamoLib);
        pnlPrestamoLib.setLayout(pnlPrestamoLibLayout);
        pnlPrestamoLibLayout.setHorizontalGroup(
            pnlPrestamoLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamoLibLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrestamoLib)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnlPrestamoLibLayout.setVerticalGroup(
            pnlPrestamoLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamoLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrestamoLibLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrestamoLib)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrestamoLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 50));

        pnlEjemplarLib.setBackground(new java.awt.Color(13, 104, 116));
        pnlEjemplarLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEjemplarLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEjemplarLibMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEjemplarLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEjemplarLibMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroEjemplar.png"))); // NOI18N

        lblEjemplarLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblEjemplarLib.setForeground(new java.awt.Color(255, 255, 255));
        lblEjemplarLib.setText("Ejemplar");

        javax.swing.GroupLayout pnlEjemplarLibLayout = new javax.swing.GroupLayout(pnlEjemplarLib);
        pnlEjemplarLib.setLayout(pnlEjemplarLibLayout);
        pnlEjemplarLibLayout.setHorizontalGroup(
            pnlEjemplarLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjemplarLibLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEjemplarLib)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnlEjemplarLibLayout.setVerticalGroup(
            pnlEjemplarLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlEjemplarLibLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEjemplarLib)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(pnlEjemplarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 50));

        pnlLibrosLib.setBackground(new java.awt.Color(13, 104, 116));
        pnlLibrosLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLibrosLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLibrosLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLibrosLibMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libro.png"))); // NOI18N

        lblLibrosLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblLibrosLib.setForeground(new java.awt.Color(255, 255, 255));
        lblLibrosLib.setText("Libros");

        javax.swing.GroupLayout pnlLibrosLibLayout = new javax.swing.GroupLayout(pnlLibrosLib);
        pnlLibrosLib.setLayout(pnlLibrosLibLayout);
        pnlLibrosLibLayout.setHorizontalGroup(
            pnlLibrosLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibrosLibLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblLibrosLib)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlLibrosLibLayout.setVerticalGroup(
            pnlLibrosLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibrosLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlLibrosLibLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLibrosLib)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlLibrosLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 50));

        btn_biblio.setBackground(new java.awt.Color(13, 104, 116));
        btn_biblio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_biblio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_biblioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_biblioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_biblioMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-biblioteca.png"))); // NOI18N

        lblBiblioLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblBiblioLib.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblioLib.setText("Biblioteca");

        javax.swing.GroupLayout btn_biblioLayout = new javax.swing.GroupLayout(btn_biblio);
        btn_biblio.setLayout(btn_biblioLayout);
        btn_biblioLayout.setHorizontalGroup(
            btn_biblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_biblioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblBiblioLib)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        btn_biblioLayout.setVerticalGroup(
            btn_biblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_biblioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_biblioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBiblioLib)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(btn_biblio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 50));

        pnlUsuarioLib.setBackground(new java.awt.Color(13, 104, 116));
        pnlUsuarioLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUsuarioLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUsuarioLibMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUsuarioLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUsuarioLibMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoclaro.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Usuario");

        javax.swing.GroupLayout pnlUsuarioLibLayout = new javax.swing.GroupLayout(pnlUsuarioLib);
        pnlUsuarioLib.setLayout(pnlUsuarioLibLayout);
        pnlUsuarioLibLayout.setHorizontalGroup(
            pnlUsuarioLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLibLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlUsuarioLibLayout.setVerticalGroup(
            pnlUsuarioLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlUsuarioLibLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlUsuarioLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 50));

        pnlPrincipalLib.setBackground(new java.awt.Color(13, 104, 116));
        pnlPrincipalLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPrincipalLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPrincipalLibMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrincipalLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrincipalLibMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-casa.png"))); // NOI18N

        lblPrincipalLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrincipalLib.setForeground(new java.awt.Color(255, 255, 255));
        lblPrincipalLib.setText("Principal");

        javax.swing.GroupLayout pnlPrincipalLibLayout = new javax.swing.GroupLayout(pnlPrincipalLib);
        pnlPrincipalLib.setLayout(pnlPrincipalLibLayout);
        pnlPrincipalLibLayout.setHorizontalGroup(
            pnlPrincipalLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLibLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPrincipalLib)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlPrincipalLibLayout.setVerticalGroup(
            pnlPrincipalLibLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalLibLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalLibLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrincipalLib)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrincipalLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 50));

        PanelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PanelMenu2.jpeg"))); // NOI18N
        jPanel1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 820));

        PanelSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoHorizontal .PNG"))); // NOI18N
        jPanel1.add(PanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 780, 90));

        lblLibros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblLibros.setForeground(new java.awt.Color(255, 255, 255));
        lblLibros.setText("Ejemplares Disponibles por Libro:");
        jPanel1.add(lblLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, -1, -1));

        lblIdLibroLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdLibroLib.setForeground(new java.awt.Color(255, 255, 255));
        lblIdLibroLib.setText("Id Libro:");
        jPanel1.add(lblIdLibroLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        txtIdLibroLib.setBackground(new java.awt.Color(204, 204, 204));
        txtIdLibroLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdLibroLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtIdLibroLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 470, 20));

        txtTituloLib.setBackground(new java.awt.Color(204, 204, 204));
        txtTituloLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtTituloLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtTituloLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 470, 20));

        lblTituloLIb.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblTituloLIb.setForeground(new java.awt.Color(255, 255, 255));
        lblTituloLIb.setText("Titulo:");
        jPanel1.add(lblTituloLIb, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtAutorLib.setBackground(new java.awt.Color(204, 204, 204));
        txtAutorLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtAutorLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtAutorLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 470, 20));

        lblAutorLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblAutorLib.setForeground(new java.awt.Color(255, 255, 255));
        lblAutorLib.setText("Autor:");
        jPanel1.add(lblAutorLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        txtAnnoLib.setBackground(new java.awt.Color(204, 204, 204));
        txtAnnoLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtAnnoLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtAnnoLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 470, 20));

        lblAnnoLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblAnnoLib.setForeground(new java.awt.Color(255, 255, 255));
        lblAnnoLib.setText("Año:");
        jPanel1.add(lblAnnoLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        txtCategLibros.setBackground(new java.awt.Color(204, 204, 204));
        txtCategLibros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtCategLibros.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtCategLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 290, 220, 20));

        lblCategoriaLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblCategoriaLib.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoriaLib.setText("Categoria:");
        jPanel1.add(lblCategoriaLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        btnBuscarLib.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarLib.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarLib.setText("Buscar");
        btnBuscarLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 170, 90, 20));

        btnModificarLib.setBackground(new java.awt.Color(255, 102, 153));
        btnModificarLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnModificarLib.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-modificar.png"))); // NOI18N
        btnModificarLib.setText("Modificar");
        btnModificarLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnModificarLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnModificarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 100, 30));

        btnEliminarLib.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEliminarLib.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-20.png"))); // NOI18N
        btnEliminarLib.setText("Eliminar");
        btnEliminarLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminarLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 90, 30));

        btnLimpiarLib.setBackground(new java.awt.Color(51, 255, 102));
        btnLimpiarLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLimpiarLib.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-limpiar-20.png"))); // NOI18N
        btnLimpiarLib.setText("Limpiar");
        btnLimpiarLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiarLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimpiarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 90, 30));

        combxCategLib.setBackground(new java.awt.Color(204, 204, 204));
        combxCategLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        combxCategLib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combxCategLibActionPerformed(evt);
            }
        });
        jPanel1.add(combxCategLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 290, 230, 20));

        btnRegistrarLib.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrarLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistrarLib.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registro-20.png"))); // NOI18N
        btnRegistrarLib.setText("Registrar");
        btnRegistrarLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistrarLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRegistrarLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 330, 100, 30));

        tblLibrosLib.setBackground(new java.awt.Color(51, 51, 51));
        tblLibrosLib.setForeground(new java.awt.Color(255, 255, 255));
        tblLibrosLib.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Libro", "Titulo", "Autor", "Año", "Categoria"
            }
        ));
        tblLibrosLib.setSelectionBackground(new java.awt.Color(13, 104, 116));
        jScrollPane1.setViewportView(tblLibrosLib);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 710, 220));

        txtBiblioLib.setBackground(new java.awt.Color(204, 204, 204));
        txtBiblioLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtBiblioLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtBiblioLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 130, 20));

        combxBiblioLib.setBackground(new java.awt.Color(204, 204, 204));
        combxBiblioLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(combxBiblioLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 320, 20));

        lblIdBiblioLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdBiblioLib.setForeground(new java.awt.Color(255, 255, 255));
        lblIdBiblioLib.setText("Biblioteca:");
        jPanel1.add(lblIdBiblioLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        lblCantidadLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblCantidadLib.setForeground(new java.awt.Color(255, 255, 255));
        lblCantidadLib.setText("Cantidad:");
        jPanel1.add(lblCantidadLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 470, -1, -1));

        txtCantidadLib.setBackground(new java.awt.Color(204, 204, 204));
        txtCantidadLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtCantidadLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtCantidadLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, 470, 20));

        lblLibros1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblLibros1.setForeground(new java.awt.Color(255, 255, 255));
        lblLibros1.setText("Libros");
        jPanel1.add(lblLibros1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        btnBuscarCantEj.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarCantEj.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarCantEj.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCantEj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarCantEj.setText("Buscar");
        btnBuscarCantEj.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarCantEj.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarCantEj, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 440, 90, -1));

        lblMostrarRegisLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblMostrarRegisLib.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrarRegisLib.setText("Mostrar Registro:");
        jPanel1.add(lblMostrarRegisLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 530, -1, 30));

        btnBuscarRegisLib.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarRegisLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarRegisLib.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarRegisLib.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda.png"))); // NOI18N
        btnBuscarRegisLib.setText("Buscar");
        btnBuscarRegisLib.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarRegisLib.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarRegisLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 180, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlPrincipalLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalLibMouseExited
        pnlPrincipalLib.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlPrincipalLibMouseExited

    private void pnlPrincipalLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalLibMouseEntered
        pnlPrincipalLib.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlPrincipalLibMouseEntered

    private void pnlUsuarioLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioLibMouseExited
        pnlUsuarioLib.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlUsuarioLibMouseExited

    private void pnlUsuarioLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioLibMouseEntered
        pnlUsuarioLib.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlUsuarioLibMouseEntered

    private void btn_biblioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_biblioMouseExited
        btn_biblio.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_biblioMouseExited

    private void btn_biblioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_biblioMouseEntered
        btn_biblio.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_biblioMouseEntered

    private void pnlLibrosLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosLibMouseExited
        pnlLibrosLib.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlLibrosLibMouseExited

    private void pnlLibrosLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosLibMouseEntered
        pnlLibrosLib.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlLibrosLibMouseEntered

    private void pnlEjemplarLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarLibMouseExited
        pnlEjemplarLib.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlEjemplarLibMouseExited

    private void pnlEjemplarLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarLibMouseEntered
        pnlEjemplarLib.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlEjemplarLibMouseEntered

    private void pnlPrestamoLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoLibMouseExited
        pnlPrestamoLib.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlPrestamoLibMouseExited

    private void pnlPrestamoLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoLibMouseEntered
        pnlPrestamoLib.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlPrestamoLibMouseEntered

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void pnlPrincipalLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalLibMouseClicked
        Vista_principal vp = new Vista_principal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlPrincipalLibMouseClicked

    private void pnlUsuarioLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioLibMouseClicked
        Vista_gestionUsuario vistaU = new Vista_gestionUsuario();
        Usuario usuario = new Usuario();
        CrudUsuario consultasU = new CrudUsuario();
        
        CtrlUsuario controlU = new CtrlUsuario(vistaU,usuario, consultasU); 
        controlU.iniciar();
        
        vistaU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlUsuarioLibMouseClicked

    private void btn_biblioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_biblioMouseClicked
        Biblioteca mod = new Biblioteca();
        CrudBiblioteca modCrud = new CrudBiblioteca();
        Vista_gestionBiblioteca vis = new Vista_gestionBiblioteca();
        
        CtrlBiblioteca ctrl = new CtrlBiblioteca(mod, modCrud, vis);
        ctrl.iniciar();
        vis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_biblioMouseClicked

    private void pnlEjemplarLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarLibMouseClicked
        Ejemplar modE = new Ejemplar();
        CrudEjemplar modCrudE = new CrudEjemplar();
        Vista_gestionEjemplar visE = new Vista_gestionEjemplar();
        
        CtrlEjemplar ctrlE = new CtrlEjemplar(modE, modCrudE, visE, CtrlInicioSesion.tipoUsuario);
        ctrlE.iniciar();
        visE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlEjemplarLibMouseClicked

    private void pnlPrestamoLibMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoLibMouseClicked
        Prestamo modP = new Prestamo();
        CrudPrestamo modCP = new CrudPrestamo();
        Vista_gestionPrestamo vistaPres = new Vista_gestionPrestamo();
        
        CtrlPrestamo ctrlPres = new CtrlPrestamo(modP,modCP,vistaPres);
        ctrlPres.iniciar();
        vistaPres.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlPrestamoLibMouseClicked

    private void combxCategLibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combxCategLibActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combxCategLibActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_gestionLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanelMenu;
    private javax.swing.JLabel PanelSup;
    public javax.swing.JButton btnBuscarCantEj;
    public javax.swing.JButton btnBuscarLib;
    public javax.swing.JButton btnBuscarRegisLib;
    private javax.swing.JLabel btnCerrar;
    public javax.swing.JButton btnEliminarLib;
    public javax.swing.JButton btnLimpiarLib;
    public javax.swing.JButton btnModificarLib;
    public javax.swing.JButton btnRegistrarLib;
    private javax.swing.JPanel btn_biblio;
    private javax.swing.ButtonGroup buttonGroup1;
    public javax.swing.JComboBox<String> combxBiblioLib;
    public javax.swing.JComboBox<String> combxCategLib;
    private javax.swing.JLabel imgLogoLib;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAnnoLib;
    private javax.swing.JLabel lblAutorLib;
    private javax.swing.JLabel lblBiblioLib;
    private javax.swing.JLabel lblCantidadLib;
    private javax.swing.JLabel lblCategoriaLib;
    private javax.swing.JLabel lblEjemplarLib;
    private javax.swing.JLabel lblIdBiblioLib;
    private javax.swing.JLabel lblIdLibroLib;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblLibros1;
    private javax.swing.JLabel lblLibrosLib;
    private javax.swing.JLabel lblMostrarRegisLib;
    private javax.swing.JLabel lblPrestamoLib;
    private javax.swing.JLabel lblPrincipalLib;
    private javax.swing.JLabel lblTituloLIb;
    private javax.swing.JLabel logoBiblioLib;
    private javax.swing.JPanel pnlEjemplarLib;
    private javax.swing.JPanel pnlLibrosLib;
    private javax.swing.JPanel pnlPrestamoLib;
    private javax.swing.JPanel pnlPrincipalLib;
    private javax.swing.JPanel pnlUsuarioLib;
    public javax.swing.JTable tblLibrosLib;
    public javax.swing.JTextField txtAnnoLib;
    public javax.swing.JTextField txtAutorLib;
    public javax.swing.JTextField txtBiblioLib;
    public javax.swing.JTextField txtCantidadLib;
    public javax.swing.JTextField txtCategLibros;
    public javax.swing.JTextField txtIdLibroLib;
    public javax.swing.JTextField txtTituloLib;
    // End of variables declaration//GEN-END:variables
}
