/*
 EQUIPO NUMERO 3
    ADRIAN PEREIRA
    MAURICIO RODRIGUEZ
    ALONDRA LEON
    ANDREA VALECILLOS
    WILLIANNY CHUELLO
 */
package vista;

import controlador.CtrlUsuario;
import controlador.CtrlBiblioteca;
import controlador.CtrlInicioSesion;
import controlador.CtrlLibro;
import controlador.CtrlPrestamo;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import modelo.Biblioteca;
import modelo.Conexion;
import modelo.CrudBiblioteca;
import modelo.CrudLibro;
import modelo.CrudPrestamo;
import modelo.CrudUsuario;
import modelo.Libro;
import modelo.Prestamo;
import modelo.Usuario;

/**
 *
 * @author HP
 */
public class Vista_gestionEjemplar extends javax.swing.JFrame {

    /**
     * Creates new form Vista_gestionEjemplar
     */
    public Vista_gestionEjemplar() {
        initComponents();
        
        PreparedStatement ps = null;
        ResultSet rs = null;
        Conexion conn = new Conexion();
        Connection con = conn.getConexion();
        
        try{
            String sql = "SELECT * FROM \"Libro\"";
            ps = con.prepareStatement(sql);
            rs = ps.executeQuery();
            
            combxLibEjemplar.addItem("Seleccione Libro");
            while(rs.next())
            {
                combxLibEjemplar.addItem(rs.getString("titulo"));
            
            }
            
            rs.close();
         
        }catch(SQLException e)
        {
            System.err.println(e.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogoEjem = new javax.swing.JLabel();
        logoBiblioEjem = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        pnlPrestamoEjem = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblPrestamoEjem = new javax.swing.JLabel();
        pnlEjemplarEjem = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblEjemplarEjem = new javax.swing.JLabel();
        pnlLibrosEjem = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblLibrosEjem = new javax.swing.JLabel();
        pnlBiblioEjem = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblBiblioEjem = new javax.swing.JLabel();
        pnlUsuarioEjem = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuarioEjem = new javax.swing.JLabel();
        pnlPrincipalEjem = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPrincipalEjem = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JLabel();
        PanelSup = new javax.swing.JLabel();
        lblEjemplar = new javax.swing.JLabel();
        lblIdEjemplarEjem = new javax.swing.JLabel();
        lblIdLibroEjem = new javax.swing.JLabel();
        lblEstadoEjem = new javax.swing.JLabel();
        txtIdEjemplarEjem = new javax.swing.JTextField();
        txtIdLibroEjem = new javax.swing.JTextField();
        txtEstadoEjem = new javax.swing.JTextField();
        btnRegistrarEjem = new javax.swing.JButton();
        btnModificarEjem = new javax.swing.JButton();
        btnEliminarEjem = new javax.swing.JButton();
        btnLimpiarEjem = new javax.swing.JButton();
        btnBuscarEjem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblEjemplarEjem = new javax.swing.JTable();
        lblUbicacionEjem = new javax.swing.JLabel();
        txtUbicacionEjem = new javax.swing.JTextField();
        combxLibEjemplar = new javax.swing.JComboBox<>();
        lblMostrarRegisEjem = new javax.swing.JLabel();
        btnBuscarRegisEjem = new javax.swing.JButton();
        combxEstadoEjemplar = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(imgLogoEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 100));

        logoBiblioEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        logoBiblioEjem.setForeground(new java.awt.Color(0, 204, 204));
        logoBiblioEjem.setText("Bibliotecas");
        jPanel1.add(logoBiblioEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 40));

        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        pnlPrestamoEjem.setBackground(new java.awt.Color(13, 104, 116));
        pnlPrestamoEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPrestamoEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPrestamoEjemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrestamoEjemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrestamoEjemMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroPrestamo.png"))); // NOI18N

        lblPrestamoEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrestamoEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestamoEjem.setText("Prestamo");

        javax.swing.GroupLayout pnlPrestamoEjemLayout = new javax.swing.GroupLayout(pnlPrestamoEjem);
        pnlPrestamoEjem.setLayout(pnlPrestamoEjemLayout);
        pnlPrestamoEjemLayout.setHorizontalGroup(
            pnlPrestamoEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamoEjemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrestamoEjem)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        pnlPrestamoEjemLayout.setVerticalGroup(
            pnlPrestamoEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamoEjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrestamoEjemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrestamoEjem)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrestamoEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 50));

        pnlEjemplarEjem.setBackground(new java.awt.Color(13, 104, 116));
        pnlEjemplarEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEjemplarEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEjemplarEjemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEjemplarEjemMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroEjemplar.png"))); // NOI18N

        lblEjemplarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblEjemplarEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblEjemplarEjem.setText("Ejemplar");

        javax.swing.GroupLayout pnlEjemplarEjemLayout = new javax.swing.GroupLayout(pnlEjemplarEjem);
        pnlEjemplarEjem.setLayout(pnlEjemplarEjemLayout);
        pnlEjemplarEjemLayout.setHorizontalGroup(
            pnlEjemplarEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjemplarEjemLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEjemplarEjem)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlEjemplarEjemLayout.setVerticalGroup(
            pnlEjemplarEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlEjemplarEjemLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEjemplarEjem)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(pnlEjemplarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 50));

        pnlLibrosEjem.setBackground(new java.awt.Color(13, 104, 116));
        pnlLibrosEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLibrosEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLibrosEjemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLibrosEjemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLibrosEjemMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libro.png"))); // NOI18N

        lblLibrosEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblLibrosEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblLibrosEjem.setText("Libros");

        javax.swing.GroupLayout pnlLibrosEjemLayout = new javax.swing.GroupLayout(pnlLibrosEjem);
        pnlLibrosEjem.setLayout(pnlLibrosEjemLayout);
        pnlLibrosEjemLayout.setHorizontalGroup(
            pnlLibrosEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibrosEjemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblLibrosEjem)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        pnlLibrosEjemLayout.setVerticalGroup(
            pnlLibrosEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibrosEjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlLibrosEjemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLibrosEjem)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlLibrosEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 50));

        pnlBiblioEjem.setBackground(new java.awt.Color(13, 104, 116));
        pnlBiblioEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBiblioEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBiblioEjemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBiblioEjemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBiblioEjemMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-biblioteca.png"))); // NOI18N

        lblBiblioEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblBiblioEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblioEjem.setText("Biblioteca");

        javax.swing.GroupLayout pnlBiblioEjemLayout = new javax.swing.GroupLayout(pnlBiblioEjem);
        pnlBiblioEjem.setLayout(pnlBiblioEjemLayout);
        pnlBiblioEjemLayout.setHorizontalGroup(
            pnlBiblioEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBiblioEjemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblBiblioEjem)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        pnlBiblioEjemLayout.setVerticalGroup(
            pnlBiblioEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBiblioEjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlBiblioEjemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBiblioEjem)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlBiblioEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 50));

        pnlUsuarioEjem.setBackground(new java.awt.Color(13, 104, 116));
        pnlUsuarioEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUsuarioEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUsuarioEjemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUsuarioEjemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUsuarioEjemMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoclaro.png"))); // NOI18N

        lblUsuarioEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblUsuarioEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioEjem.setText("Usuario");

        javax.swing.GroupLayout pnlUsuarioEjemLayout = new javax.swing.GroupLayout(pnlUsuarioEjem);
        pnlUsuarioEjem.setLayout(pnlUsuarioEjemLayout);
        pnlUsuarioEjemLayout.setHorizontalGroup(
            pnlUsuarioEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioEjemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioEjem)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlUsuarioEjemLayout.setVerticalGroup(
            pnlUsuarioEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioEjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlUsuarioEjemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUsuarioEjem)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlUsuarioEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 50));

        pnlPrincipalEjem.setBackground(new java.awt.Color(13, 104, 116));
        pnlPrincipalEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPrincipalEjem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPrincipalEjemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrincipalEjemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrincipalEjemMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-casa.png"))); // NOI18N

        lblPrincipalEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrincipalEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblPrincipalEjem.setText("Principal");

        javax.swing.GroupLayout pnlPrincipalEjemLayout = new javax.swing.GroupLayout(pnlPrincipalEjem);
        pnlPrincipalEjem.setLayout(pnlPrincipalEjemLayout);
        pnlPrincipalEjemLayout.setHorizontalGroup(
            pnlPrincipalEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalEjemLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPrincipalEjem)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        pnlPrincipalEjemLayout.setVerticalGroup(
            pnlPrincipalEjemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalEjemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalEjemLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrincipalEjem)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrincipalEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 50));

        PanelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PanelMenu.jpeg"))); // NOI18N
        jPanel1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        PanelSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoHorizontal .PNG"))); // NOI18N
        jPanel1.add(PanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 810, 90));

        lblEjemplar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblEjemplar.setForeground(new java.awt.Color(255, 255, 255));
        lblEjemplar.setText("Ejemplar");
        jPanel1.add(lblEjemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        lblIdEjemplarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdEjemplarEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblIdEjemplarEjem.setText("Id Ejemplar:");
        jPanel1.add(lblIdEjemplarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        lblIdLibroEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdLibroEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblIdLibroEjem.setText("Libro:");
        jPanel1.add(lblIdLibroEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        lblEstadoEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblEstadoEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoEjem.setText("Estado:");
        jPanel1.add(lblEstadoEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtIdEjemplarEjem.setBackground(new java.awt.Color(204, 204, 204));
        txtIdEjemplarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdEjemplarEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtIdEjemplarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 490, 20));

        txtIdLibroEjem.setBackground(new java.awt.Color(204, 204, 204));
        txtIdLibroEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdLibroEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtIdLibroEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 260, 150, 20));

        txtEstadoEjem.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtEstadoEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtEstadoEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 150, 20));

        btnRegistrarEjem.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistrarEjem.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registro-20.png"))); // NOI18N
        btnRegistrarEjem.setText("Registrar");
        btnRegistrarEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistrarEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRegistrarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 100, 30));

        btnModificarEjem.setBackground(new java.awt.Color(255, 102, 153));
        btnModificarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnModificarEjem.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-modificar.png"))); // NOI18N
        btnModificarEjem.setText("Modificar");
        btnModificarEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnModificarEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnModificarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, 90, 30));

        btnEliminarEjem.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEliminarEjem.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-20.png"))); // NOI18N
        btnEliminarEjem.setText("Eliminar");
        btnEliminarEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminarEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 300, 90, 30));

        btnLimpiarEjem.setBackground(new java.awt.Color(51, 255, 102));
        btnLimpiarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLimpiarEjem.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-limpiar-20.png"))); // NOI18N
        btnLimpiarEjem.setText("Limpiar");
        btnLimpiarEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiarEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimpiarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 300, 90, 30));

        btnBuscarEjem.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarEjem.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarEjem.setText("Buscar");
        btnBuscarEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 170, 90, 20));

        tblEjemplarEjem.setBackground(new java.awt.Color(51, 51, 51));
        tblEjemplarEjem.setForeground(new java.awt.Color(255, 255, 255));
        tblEjemplarEjem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id Ejemplar", "Id Libro", "Estado", "Ubicación"
            }
        ));
        tblEjemplarEjem.setSelectionBackground(new java.awt.Color(13, 104, 116));
        jScrollPane1.setViewportView(tblEjemplarEjem);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, 720, 170));

        lblUbicacionEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblUbicacionEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblUbicacionEjem.setText("Ubicación:");
        jPanel1.add(lblUbicacionEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        txtUbicacionEjem.setBackground(new java.awt.Color(204, 204, 204));
        txtUbicacionEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtUbicacionEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtUbicacionEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 490, 20));

        combxLibEjemplar.setBackground(new java.awt.Color(204, 204, 204));
        combxLibEjemplar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        combxLibEjemplar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combxLibEjemplarActionPerformed(evt);
            }
        });
        jPanel1.add(combxLibEjemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 320, 20));

        lblMostrarRegisEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblMostrarRegisEjem.setForeground(new java.awt.Color(255, 255, 255));
        lblMostrarRegisEjem.setText("Mostrar Registro:");
        jPanel1.add(lblMostrarRegisEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, 30));

        btnBuscarRegisEjem.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarRegisEjem.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarRegisEjem.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarRegisEjem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda.png"))); // NOI18N
        btnBuscarRegisEjem.setText("Buscar");
        btnBuscarRegisEjem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarRegisEjem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarRegisEjem, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, 180, 30));

        combxEstadoEjemplar.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(combxEstadoEjemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 320, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void pnlPrestamoEjemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoEjemMouseEntered
        pnlPrestamoEjem.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlPrestamoEjemMouseEntered

    private void pnlPrestamoEjemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoEjemMouseExited
        pnlPrestamoEjem.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlPrestamoEjemMouseExited

    private void pnlEjemplarEjemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarEjemMouseEntered
        pnlEjemplarEjem.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlEjemplarEjemMouseEntered

    private void pnlEjemplarEjemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarEjemMouseExited
        pnlEjemplarEjem.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlEjemplarEjemMouseExited

    private void pnlLibrosEjemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosEjemMouseEntered
        pnlLibrosEjem.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlLibrosEjemMouseEntered

    private void pnlLibrosEjemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosEjemMouseExited
        pnlLibrosEjem.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlLibrosEjemMouseExited

    private void pnlBiblioEjemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiblioEjemMouseEntered
        pnlBiblioEjem.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlBiblioEjemMouseEntered

    private void pnlBiblioEjemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiblioEjemMouseExited
        pnlBiblioEjem.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlBiblioEjemMouseExited

    private void pnlUsuarioEjemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioEjemMouseEntered
        pnlUsuarioEjem.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlUsuarioEjemMouseEntered

    private void pnlUsuarioEjemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioEjemMouseExited
        pnlUsuarioEjem.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlUsuarioEjemMouseExited

    private void pnlPrincipalEjemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalEjemMouseEntered
        pnlPrincipalEjem.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlPrincipalEjemMouseEntered

    private void pnlPrincipalEjemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalEjemMouseExited
        pnlPrincipalEjem.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlPrincipalEjemMouseExited

    private void pnlPrincipalEjemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalEjemMouseClicked
        Vista_principal vp = new Vista_principal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlPrincipalEjemMouseClicked

    private void pnlUsuarioEjemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioEjemMouseClicked
        Vista_gestionUsuario vistaU = new Vista_gestionUsuario();
        Usuario usuario = new Usuario();
        CrudUsuario consultasU = new CrudUsuario();
        
        CtrlUsuario controlU = new CtrlUsuario(vistaU,usuario, consultasU); 
        controlU.iniciar();
        
        vistaU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlUsuarioEjemMouseClicked

    private void pnlBiblioEjemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiblioEjemMouseClicked
        Biblioteca mod = new Biblioteca();
        CrudBiblioteca modCrud = new CrudBiblioteca();
        Vista_gestionBiblioteca vis = new Vista_gestionBiblioteca();
        
        CtrlBiblioteca ctrl = new CtrlBiblioteca(mod, modCrud, vis);
        ctrl.iniciar();
        vis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlBiblioEjemMouseClicked

    private void pnlLibrosEjemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosEjemMouseClicked
        Libro modL = new Libro();
        CrudLibro modCrudL = new CrudLibro();
        Vista_gestionLibros visL = new Vista_gestionLibros();

        CtrlLibro ctrlL = new CtrlLibro(modL, modCrudL, visL, CtrlInicioSesion.tipoUsuario);
        ctrlL.iniciar();
        visL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlLibrosEjemMouseClicked

    private void pnlPrestamoEjemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoEjemMouseClicked
        Prestamo modP = new Prestamo();
        CrudPrestamo modCP = new CrudPrestamo();
        Vista_gestionPrestamo vistaPres = new Vista_gestionPrestamo();
        
        CtrlPrestamo ctrlPres = new CtrlPrestamo(modP,modCP,vistaPres);
        ctrlPres.iniciar();
        vistaPres.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlPrestamoEjemMouseClicked

    private void combxLibEjemplarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combxLibEjemplarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combxLibEjemplarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionEjemplar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_gestionEjemplar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanelMenu;
    private javax.swing.JLabel PanelSup;
    public javax.swing.JButton btnBuscarEjem;
    public javax.swing.JButton btnBuscarRegisEjem;
    private javax.swing.JLabel btnCerrar;
    public javax.swing.JButton btnEliminarEjem;
    public javax.swing.JButton btnLimpiarEjem;
    public javax.swing.JButton btnModificarEjem;
    public javax.swing.JButton btnRegistrarEjem;
    public javax.swing.JComboBox<String> combxEstadoEjemplar;
    public javax.swing.JComboBox<String> combxLibEjemplar;
    private javax.swing.JLabel imgLogoEjem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBiblioEjem;
    private javax.swing.JLabel lblEjemplar;
    private javax.swing.JLabel lblEjemplarEjem;
    private javax.swing.JLabel lblEstadoEjem;
    private javax.swing.JLabel lblIdEjemplarEjem;
    private javax.swing.JLabel lblIdLibroEjem;
    private javax.swing.JLabel lblLibrosEjem;
    private javax.swing.JLabel lblMostrarRegisEjem;
    private javax.swing.JLabel lblPrestamoEjem;
    private javax.swing.JLabel lblPrincipalEjem;
    private javax.swing.JLabel lblUbicacionEjem;
    private javax.swing.JLabel lblUsuarioEjem;
    private javax.swing.JLabel logoBiblioEjem;
    private javax.swing.JPanel pnlBiblioEjem;
    private javax.swing.JPanel pnlEjemplarEjem;
    private javax.swing.JPanel pnlLibrosEjem;
    private javax.swing.JPanel pnlPrestamoEjem;
    private javax.swing.JPanel pnlPrincipalEjem;
    private javax.swing.JPanel pnlUsuarioEjem;
    public javax.swing.JTable tblEjemplarEjem;
    public javax.swing.JTextField txtEstadoEjem;
    public javax.swing.JTextField txtIdEjemplarEjem;
    public javax.swing.JTextField txtIdLibroEjem;
    public javax.swing.JTextField txtUbicacionEjem;
    // End of variables declaration//GEN-END:variables
}
