/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import java.awt.Color;

/**
 *
 * @author HP
 */
public class Vista_gestionPrestamo extends javax.swing.JFrame {

    /**
     * Creates new form Vista_gestionPrestamo
     */
    public Vista_gestionPrestamo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogoPrest = new javax.swing.JLabel();
        logoBiblioPrest = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        pnlPrestamoPrest = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblPrestamoPrest = new javax.swing.JLabel();
        pnlEjemplarPrest = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblEjemplarPrest = new javax.swing.JLabel();
        pnlLibrosPrest = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblLibrosPrest = new javax.swing.JLabel();
        pnlBiblioPrest = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblBiblioPrest = new javax.swing.JLabel();
        pnlUsuarioPrest = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuarioPrest = new javax.swing.JLabel();
        pnlPrincipalPrest = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPrincipalPrest = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JLabel();
        PanelSup = new javax.swing.JLabel();
        lblPrestamo = new javax.swing.JLabel();
        lblIdPrest = new javax.swing.JLabel();
        txtIdPrest = new javax.swing.JTextField();
        txtCedulaPrest = new javax.swing.JTextField();
        lblCedulaPrest = new javax.swing.JLabel();
        txtIdEjemplarPrest = new javax.swing.JTextField();
        lblIdEjemplarPrest = new javax.swing.JLabel();
        txtFchEntregaPrest = new javax.swing.JTextField();
        lblFchEntregaPrest = new javax.swing.JLabel();
        txtEstadoPrest = new javax.swing.JTextField();
        lblEstadoPrest = new javax.swing.JLabel();
        txtBuscarPrest = new javax.swing.JTextField();
        btnIdEjemPrest = new javax.swing.JButton();
        btnModificarPrest = new javax.swing.JButton();
        btnEliminarPrest = new javax.swing.JButton();
        btnLimpiarPrest = new javax.swing.JButton();
        btnRegistrarPrest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPrestamoPrest = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        lblRenovPrest = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        btnBuscarMultaPrest = new javax.swing.JButton();
        btnBuscarIdPrest = new javax.swing.JButton();
        btnBuscarCedulaPrest = new javax.swing.JButton();
        btnBuscarRegisPrest = new javax.swing.JButton();
        btnBuscarRenovPrest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(imgLogoPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 100));

        logoBiblioPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        logoBiblioPrest.setForeground(new java.awt.Color(0, 204, 204));
        logoBiblioPrest.setText("Bibliotecas");
        jPanel1.add(logoBiblioPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 40));

        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 10, -1, -1));

        pnlPrestamoPrest.setBackground(new java.awt.Color(13, 104, 116));
        pnlPrestamoPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPrestamoPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrestamoPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrestamoPrestMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroPrestamo.png"))); // NOI18N

        lblPrestamoPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrestamoPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestamoPrest.setText("Prestamo");

        javax.swing.GroupLayout pnlPrestamoPrestLayout = new javax.swing.GroupLayout(pnlPrestamoPrest);
        pnlPrestamoPrest.setLayout(pnlPrestamoPrestLayout);
        pnlPrestamoPrestLayout.setHorizontalGroup(
            pnlPrestamoPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamoPrestLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrestamoPrest)
                .addContainerGap(88, Short.MAX_VALUE))
        );
        pnlPrestamoPrestLayout.setVerticalGroup(
            pnlPrestamoPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrestamoPrestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrestamoPrestLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrestamoPrest)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrestamoPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 50));

        pnlEjemplarPrest.setBackground(new java.awt.Color(13, 104, 116));
        pnlEjemplarPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlEjemplarPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEjemplarPrestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlEjemplarPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlEjemplarPrestMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroEjemplar.png"))); // NOI18N

        lblEjemplarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblEjemplarPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblEjemplarPrest.setText("Ejemplar");

        javax.swing.GroupLayout pnlEjemplarPrestLayout = new javax.swing.GroupLayout(pnlEjemplarPrest);
        pnlEjemplarPrest.setLayout(pnlEjemplarPrestLayout);
        pnlEjemplarPrestLayout.setHorizontalGroup(
            pnlEjemplarPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEjemplarPrestLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEjemplarPrest)
                .addContainerGap(95, Short.MAX_VALUE))
        );
        pnlEjemplarPrestLayout.setVerticalGroup(
            pnlEjemplarPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlEjemplarPrestLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEjemplarPrest)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(pnlEjemplarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 250, 50));

        pnlLibrosPrest.setBackground(new java.awt.Color(13, 104, 116));
        pnlLibrosPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlLibrosPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlLibrosPrestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlLibrosPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlLibrosPrestMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libro.png"))); // NOI18N

        lblLibrosPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblLibrosPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblLibrosPrest.setText("Libros");

        javax.swing.GroupLayout pnlLibrosPrestLayout = new javax.swing.GroupLayout(pnlLibrosPrest);
        pnlLibrosPrest.setLayout(pnlLibrosPrestLayout);
        pnlLibrosPrestLayout.setHorizontalGroup(
            pnlLibrosPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibrosPrestLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblLibrosPrest)
                .addContainerGap(120, Short.MAX_VALUE))
        );
        pnlLibrosPrestLayout.setVerticalGroup(
            pnlLibrosPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlLibrosPrestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlLibrosPrestLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLibrosPrest)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlLibrosPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 50));

        pnlBiblioPrest.setBackground(new java.awt.Color(13, 104, 116));
        pnlBiblioPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlBiblioPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlBiblioPrestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlBiblioPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlBiblioPrestMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-biblioteca.png"))); // NOI18N

        lblBiblioPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblBiblioPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblioPrest.setText("Biblioteca");

        javax.swing.GroupLayout pnlBiblioPrestLayout = new javax.swing.GroupLayout(pnlBiblioPrest);
        pnlBiblioPrest.setLayout(pnlBiblioPrestLayout);
        pnlBiblioPrestLayout.setHorizontalGroup(
            pnlBiblioPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBiblioPrestLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblBiblioPrest)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlBiblioPrestLayout.setVerticalGroup(
            pnlBiblioPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBiblioPrestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlBiblioPrestLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBiblioPrest)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlBiblioPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 250, 50));

        pnlUsuarioPrest.setBackground(new java.awt.Color(13, 104, 116));
        pnlUsuarioPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlUsuarioPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlUsuarioPrestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlUsuarioPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlUsuarioPrestMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoclaro.png"))); // NOI18N

        lblUsuarioPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblUsuarioPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuarioPrest.setText("Usuario");

        javax.swing.GroupLayout pnlUsuarioPrestLayout = new javax.swing.GroupLayout(pnlUsuarioPrest);
        pnlUsuarioPrest.setLayout(pnlUsuarioPrestLayout);
        pnlUsuarioPrestLayout.setHorizontalGroup(
            pnlUsuarioPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioPrestLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblUsuarioPrest)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        pnlUsuarioPrestLayout.setVerticalGroup(
            pnlUsuarioPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlUsuarioPrestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlUsuarioPrestLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUsuarioPrest)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlUsuarioPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 50));

        pnlPrincipalPrest.setBackground(new java.awt.Color(13, 104, 116));
        pnlPrincipalPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnlPrincipalPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlPrincipalPrestMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pnlPrincipalPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pnlPrincipalPrestMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-casa.png"))); // NOI18N

        lblPrincipalPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrincipalPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblPrincipalPrest.setText("Principal");

        javax.swing.GroupLayout pnlPrincipalPrestLayout = new javax.swing.GroupLayout(pnlPrincipalPrest);
        pnlPrincipalPrest.setLayout(pnlPrincipalPrestLayout);
        pnlPrincipalPrestLayout.setHorizontalGroup(
            pnlPrincipalPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPrestLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPrincipalPrest)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        pnlPrincipalPrestLayout.setVerticalGroup(
            pnlPrincipalPrestLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPrincipalPrestLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(pnlPrincipalPrestLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrincipalPrest)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(pnlPrincipalPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 250, 50));

        PanelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PanelMenu2.jpeg"))); // NOI18N
        jPanel1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 760));

        PanelSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoHorizontal .PNG"))); // NOI18N
        jPanel1.add(PanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 780, 90));

        lblPrestamo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestamo.setText("Prestamo");
        jPanel1.add(lblPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        lblIdPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblIdPrest.setText("Id Prestamo:");
        jPanel1.add(lblIdPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, -1));

        txtIdPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtIdPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtIdPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 450, 20));

        txtCedulaPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtCedulaPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtCedulaPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtCedulaPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 450, 20));

        lblCedulaPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblCedulaPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblCedulaPrest.setText("Cedula:");
        jPanel1.add(lblCedulaPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        txtIdEjemplarPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtIdEjemplarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdEjemplarPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtIdEjemplarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 450, 20));

        lblIdEjemplarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdEjemplarPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblIdEjemplarPrest.setText("Id Ejemplar:");
        jPanel1.add(lblIdEjemplarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        txtFchEntregaPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtFchEntregaPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtFchEntregaPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtFchEntregaPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 260, 450, 20));

        lblFchEntregaPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblFchEntregaPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblFchEntregaPrest.setText("Fecha de Entrega:");
        jPanel1.add(lblFchEntregaPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        txtEstadoPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtEstadoPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtEstadoPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(txtEstadoPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 290, 450, 20));

        lblEstadoPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblEstadoPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblEstadoPrest.setText("Estado de Prestamo:");
        jPanel1.add(lblEstadoPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        txtBuscarPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtBuscarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtBuscarPrest.setText("Insertar Registro");
        txtBuscarPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txtBuscarPrest.setEnabled(false);
        jPanel1.add(txtBuscarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, 600, 30));

        btnIdEjemPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnIdEjemPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnIdEjemPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnIdEjemPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnIdEjemPrest.setText("Buscar");
        btnIdEjemPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnIdEjemPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnIdEjemPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, 90, 20));

        btnModificarPrest.setBackground(new java.awt.Color(255, 102, 153));
        btnModificarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnModificarPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-modificar.png"))); // NOI18N
        btnModificarPrest.setText("Modificar");
        btnModificarPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnModificarPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnModificarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, 100, 30));

        btnEliminarPrest.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEliminarPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-20.png"))); // NOI18N
        btnEliminarPrest.setText("Eliminar");
        btnEliminarPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminarPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnEliminarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 330, 100, 30));

        btnLimpiarPrest.setBackground(new java.awt.Color(51, 255, 102));
        btnLimpiarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLimpiarPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-limpiar-20.png"))); // NOI18N
        btnLimpiarPrest.setText("Limpiar");
        btnLimpiarPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiarPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnLimpiarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 90, 30));

        btnRegistrarPrest.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrarPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistrarPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registro-20.png"))); // NOI18N
        btnRegistrarPrest.setText("Registrar");
        btnRegistrarPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistrarPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnRegistrarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 100, 30));

        tblPrestamoPrest.setBackground(new java.awt.Color(51, 51, 51));
        tblPrestamoPrest.setForeground(new java.awt.Color(255, 255, 255));
        tblPrestamoPrest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id Prestamo", "Cedula", "Id Ejemplar", "Fecha de Salida", "Fecha Venc", "Fecha Entrega", "Id.Est.Prestamo", "Estado del Prestamo"
            }
        ));
        tblPrestamoPrest.setSelectionBackground(new java.awt.Color(13, 104, 116));
        jScrollPane1.setViewportView(tblPrestamoPrest);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 710, 200));

        jTable2.setBackground(new java.awt.Color(51, 51, 51));
        jTable2.setForeground(new java.awt.Color(255, 255, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id Libro", "Cedula", "Id Ejemplar", "Fecha de Entrega", "Estado de Prestamo"
            }
        ));
        jTable2.setSelectionBackground(new java.awt.Color(13, 104, 116));
        jScrollPane2.setViewportView(jTable2);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 520, 710, 200));

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Cedula:");
        jPanel1.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, -1));

        jTextField6.setBackground(new java.awt.Color(204, 204, 204));
        jTextField6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTextField6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 450, 20));

        jTextField8.setBackground(new java.awt.Color(204, 204, 204));
        jTextField8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 200, 450, 20));

        lblRenovPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblRenovPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblRenovPrest.setText("Renovación:");
        jPanel1.add(lblRenovPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 410, -1, 30));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Multa:");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 410, -1, 30));

        btnBuscarMultaPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarMultaPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarMultaPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarMultaPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda.png"))); // NOI18N
        btnBuscarMultaPrest.setText("Buscar");
        btnBuscarMultaPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarMultaPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarMultaPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarMultaPrestMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarMultaPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 410, 160, 30));

        btnBuscarIdPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarIdPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarIdPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarIdPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarIdPrest.setText("Buscar");
        btnBuscarIdPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarIdPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarIdPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 168, 90, -1));

        btnBuscarCedulaPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarCedulaPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarCedulaPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarCedulaPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarCedulaPrest.setText("Buscar");
        btnBuscarCedulaPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarCedulaPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarCedulaPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 200, 90, 20));

        btnBuscarRegisPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarRegisPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarRegisPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarRegisPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda.png"))); // NOI18N
        btnBuscarRegisPrest.setText("Buscar");
        btnBuscarRegisPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarRegisPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(btnBuscarRegisPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 480, 90, 30));

        btnBuscarRenovPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarRenovPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarRenovPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarRenovPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda.png"))); // NOI18N
        btnBuscarRenovPrest.setText("Buscar");
        btnBuscarRenovPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarRenovPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscarRenovPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarRenovPrestMouseClicked(evt);
            }
        });
        jPanel1.add(btnBuscarRenovPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 410, 160, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pnlPrincipalPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalPrestMouseExited
        pnlPrincipalPrest.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlPrincipalPrestMouseExited

    private void pnlPrincipalPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalPrestMouseEntered
        pnlPrincipalPrest.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlPrincipalPrestMouseEntered

    private void pnlUsuarioPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioPrestMouseExited
        pnlUsuarioPrest.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlUsuarioPrestMouseExited

    private void pnlUsuarioPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioPrestMouseEntered
        pnlUsuarioPrest.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlUsuarioPrestMouseEntered

    private void pnlBiblioPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiblioPrestMouseExited
        pnlBiblioPrest.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlBiblioPrestMouseExited

    private void pnlBiblioPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiblioPrestMouseEntered
        pnlBiblioPrest.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlBiblioPrestMouseEntered

    private void pnlLibrosPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosPrestMouseExited
        pnlLibrosPrest.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlLibrosPrestMouseExited

    private void pnlLibrosPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosPrestMouseEntered
        pnlLibrosPrest.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlLibrosPrestMouseEntered

    private void pnlEjemplarPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarPrestMouseExited
        pnlEjemplarPrest.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlEjemplarPrestMouseExited

    private void pnlEjemplarPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarPrestMouseEntered
        pnlEjemplarPrest.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlEjemplarPrestMouseEntered

    private void pnlPrestamoPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoPrestMouseExited
        pnlPrestamoPrest.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_pnlPrestamoPrestMouseExited

    private void pnlPrestamoPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrestamoPrestMouseEntered
        pnlPrestamoPrest.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_pnlPrestamoPrestMouseEntered

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void pnlPrincipalPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlPrincipalPrestMouseClicked
        Vista_principal vp = new Vista_principal();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlPrincipalPrestMouseClicked

    private void pnlUsuarioPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlUsuarioPrestMouseClicked
        Vista_gestionUsuario vu = new Vista_gestionUsuario();
        vu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlUsuarioPrestMouseClicked

    private void pnlBiblioPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBiblioPrestMouseClicked
        Vista_gestionBiblioteca vb = new Vista_gestionBiblioteca();
        vb.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlBiblioPrestMouseClicked

    private void pnlLibrosPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlLibrosPrestMouseClicked
        Vista_gestionEjemplar ve = new Vista_gestionEjemplar();
        ve.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlLibrosPrestMouseClicked

    private void pnlEjemplarPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEjemplarPrestMouseClicked
        Vista_gestionEjemplar ve = new Vista_gestionEjemplar();
        ve.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pnlEjemplarPrestMouseClicked

    private void btnBuscarRenovPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarRenovPrestMouseClicked
        Vista_emergenteRenovacion vr = new Vista_emergenteRenovacion();
        vr.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarRenovPrestMouseClicked

    private void btnBuscarMultaPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarMultaPrestMouseClicked
        Vista_emergenteMulta vm = new Vista_emergenteMulta();
        vm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBuscarMultaPrestMouseClicked

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_gestionPrestamo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_gestionPrestamo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanelMenu;
    private javax.swing.JLabel PanelSup;
    private javax.swing.JButton btnBuscarCedulaPrest;
    public javax.swing.JButton btnBuscarIdPrest;
    private javax.swing.JButton btnBuscarMultaPrest;
    public javax.swing.JButton btnBuscarRegisPrest;
    private javax.swing.JButton btnBuscarRenovPrest;
    private javax.swing.JLabel btnCerrar;
    public javax.swing.JButton btnEliminarPrest;
    private javax.swing.JButton btnIdEjemPrest;
    public javax.swing.JButton btnLimpiarPrest;
    public javax.swing.JButton btnModificarPrest;
    public javax.swing.JButton btnRegistrarPrest;
    private javax.swing.JLabel imgLogoPrest;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel lblBiblioPrest;
    private javax.swing.JLabel lblCedulaPrest;
    private javax.swing.JLabel lblEjemplarPrest;
    private javax.swing.JLabel lblEstadoPrest;
    private javax.swing.JLabel lblFchEntregaPrest;
    private javax.swing.JLabel lblIdEjemplarPrest;
    private javax.swing.JLabel lblIdPrest;
    private javax.swing.JLabel lblLibrosPrest;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblPrestamoPrest;
    private javax.swing.JLabel lblPrincipalPrest;
    private javax.swing.JLabel lblRenovPrest;
    private javax.swing.JLabel lblUsuarioPrest;
    private javax.swing.JLabel logoBiblioPrest;
    private javax.swing.JPanel pnlBiblioPrest;
    private javax.swing.JPanel pnlEjemplarPrest;
    private javax.swing.JPanel pnlLibrosPrest;
    private javax.swing.JPanel pnlPrestamoPrest;
    private javax.swing.JPanel pnlPrincipalPrest;
    private javax.swing.JPanel pnlUsuarioPrest;
    public javax.swing.JTable tblPrestamoPrest;
    private javax.swing.JTextField txtBuscarPrest;
    public javax.swing.JTextField txtCedulaPrest;
    public javax.swing.JTextField txtEstadoPrest;
    public javax.swing.JTextField txtFchEntregaPrest;
    public javax.swing.JTextField txtIdEjemplarPrest;
    public javax.swing.JTextField txtIdPrest;
    // End of variables declaration//GEN-END:variables
}
