/*
 EQUIPO NUMERO 3
    ADRIAN PEREIRA
    MAURICIO RODRIGUEZ
    ALONDRA LEON
    ANDREA VALECILLOS
    WILLIANNY CHUELLO
 */
package vista;

import com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialLighterIJTheme;
import controlador.CtrlUsuario;
import controlador.CtrlEjemplar;
import controlador.CtrlLibro;
import controlador.CtrlBiblioteca;
import controlador.CtrlInicioSesion;
import controlador.CtrlPrestamo;
import java.awt.Color;
import modelo.Biblioteca;
import modelo.CrudPrestamo;
import modelo.CrudBiblioteca;
import modelo.CrudEjemplar;
import modelo.CrudInicioSesion;
import modelo.CrudLibro;
import modelo.CrudUsuario;
import modelo.Ejemplar;
import modelo.InicioSesion;
import modelo.Libro;
import modelo.Prestamo;
import modelo.Usuario;




public class Vista_principal extends javax.swing.JFrame {
    
    /**
     * Creates new form ventana_principal
     */
    public Vista_principal() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgLogoUsu = new javax.swing.JLabel();
        logoBiblio = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JLabel();
        btn_prestamo = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lblPrestamo = new javax.swing.JLabel();
        btn_ejemplar = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lblEjemplar = new javax.swing.JLabel();
        btn_libros = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lblLibros = new javax.swing.JLabel();
        btn_biblio = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lblBiblio = new javax.swing.JLabel();
        btn_usuario = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        btn_principal = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPrincipalVista = new javax.swing.JLabel();
        lblCerrarSes = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelMenu = new javax.swing.JLabel();
        PanelSup = new javax.swing.JLabel();
        lblTtlPrest = new javax.swing.JLabel();
        lblSanc = new javax.swing.JLabel();
        lblTtlDe = new javax.swing.JLabel();
        lblTtlLibros = new javax.swing.JLabel();
        lblDisp = new javax.swing.JLabel();
        numTotalLib = new javax.swing.JLabel();
        numTotalPrest = new javax.swing.JLabel();
        numTotalSan = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        lblBienvenido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgLogoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel1.add(imgLogoUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 100));

        logoBiblio.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        logoBiblio.setForeground(new java.awt.Color(0, 204, 204));
        logoBiblio.setText("Bibliotecas");
        jPanel1.add(logoBiblio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 150, 40));

        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, -1));

        btn_prestamo.setBackground(new java.awt.Color(13, 104, 116));
        btn_prestamo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_prestamo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_prestamoMouseExited(evt);
            }
        });

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroPrestamo.png"))); // NOI18N

        lblPrestamo.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrestamo.setForeground(new java.awt.Color(255, 255, 255));
        lblPrestamo.setText("Prestamo");

        javax.swing.GroupLayout btn_prestamoLayout = new javax.swing.GroupLayout(btn_prestamo);
        btn_prestamo.setLayout(btn_prestamoLayout);
        btn_prestamoLayout.setHorizontalGroup(
            btn_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prestamoLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblPrestamo)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        btn_prestamoLayout.setVerticalGroup(
            btn_prestamoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_prestamoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_prestamoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrestamo)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(btn_prestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 50));

        btn_ejemplar.setBackground(new java.awt.Color(13, 104, 116));
        btn_ejemplar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ejemplar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_ejemplarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_ejemplarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_ejemplarMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libroEjemplar.png"))); // NOI18N

        lblEjemplar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblEjemplar.setForeground(new java.awt.Color(255, 255, 255));
        lblEjemplar.setText("Ejemplar");

        javax.swing.GroupLayout btn_ejemplarLayout = new javax.swing.GroupLayout(btn_ejemplar);
        btn_ejemplar.setLayout(btn_ejemplarLayout);
        btn_ejemplarLayout.setHorizontalGroup(
            btn_ejemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_ejemplarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEjemplar)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        btn_ejemplarLayout.setVerticalGroup(
            btn_ejemplarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(btn_ejemplarLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblEjemplar)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jPanel1.add(btn_ejemplar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 50));

        btn_libros.setBackground(new java.awt.Color(13, 104, 116));
        btn_libros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_libros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_librosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_librosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_librosMouseExited(evt);
            }
        });

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-libro.png"))); // NOI18N

        lblLibros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblLibros.setForeground(new java.awt.Color(255, 255, 255));
        lblLibros.setText("Libros");

        javax.swing.GroupLayout btn_librosLayout = new javax.swing.GroupLayout(btn_libros);
        btn_libros.setLayout(btn_librosLayout);
        btn_librosLayout.setHorizontalGroup(
            btn_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_librosLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(lblLibros)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        btn_librosLayout.setVerticalGroup(
            btn_librosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_librosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_librosLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblLibros)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(btn_libros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 50));

        btn_biblio.setBackground(new java.awt.Color(13, 104, 116));
        btn_biblio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_biblio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_biblioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_biblioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_biblioMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-biblioteca.png"))); // NOI18N

        lblBiblio.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblBiblio.setForeground(new java.awt.Color(255, 255, 255));
        lblBiblio.setText("Biblioteca");

        javax.swing.GroupLayout btn_biblioLayout = new javax.swing.GroupLayout(btn_biblio);
        btn_biblio.setLayout(btn_biblioLayout);
        btn_biblioLayout.setHorizontalGroup(
            btn_biblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_biblioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(lblBiblio)
                .addContainerGap(75, Short.MAX_VALUE))
        );
        btn_biblioLayout.setVerticalGroup(
            btn_biblioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_biblioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_biblioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblBiblio)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(btn_biblio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 240, 50));

        btn_usuario.setBackground(new java.awt.Color(13, 104, 116));
        btn_usuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_usuarioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_usuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_usuarioMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/iconoclaro.png"))); // NOI18N

        lblUsuario.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario");

        javax.swing.GroupLayout btn_usuarioLayout = new javax.swing.GroupLayout(btn_usuario);
        btn_usuario.setLayout(btn_usuarioLayout);
        btn_usuarioLayout.setHorizontalGroup(
            btn_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_usuarioLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(lblUsuario)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        btn_usuarioLayout.setVerticalGroup(
            btn_usuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_usuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_usuarioLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblUsuario)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(btn_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 240, 50));

        btn_principal.setBackground(new java.awt.Color(13, 104, 116));
        btn_principal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_principal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_principalMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_principalMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-casa.png"))); // NOI18N

        lblPrincipalVista.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblPrincipalVista.setForeground(new java.awt.Color(255, 255, 255));
        lblPrincipalVista.setText("Principal");

        javax.swing.GroupLayout btn_principalLayout = new javax.swing.GroupLayout(btn_principal);
        btn_principal.setLayout(btn_principalLayout);
        btn_principalLayout.setHorizontalGroup(
            btn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_principalLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblPrincipalVista)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        btn_principalLayout.setVerticalGroup(
            btn_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btn_principalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(btn_principalLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblPrincipalVista)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        jPanel1.add(btn_principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 240, 50));

        lblCerrarSes.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        lblCerrarSes.setForeground(new java.awt.Color(255, 255, 255));
        lblCerrarSes.setText("Cerrar Sesión");
        lblCerrarSes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarSesMouseClicked(evt);
            }
        });
        jPanel1.add(lblCerrarSes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 554, -1, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-cerrar-sesión-32.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, -1, -1));

        PanelMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/PanelMenu.jpeg"))); // NOI18N
        jPanel1.add(PanelMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 600));

        PanelSup.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoHorizontal .PNG"))); // NOI18N
        jPanel1.add(PanelSup, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 810, 90));

        lblTtlPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTtlPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblTtlPrest.setText("Total de Prestamo");
        jPanel1.add(lblTtlPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 170, 30));

        lblSanc.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblSanc.setForeground(new java.awt.Color(255, 255, 255));
        lblSanc.setText("Sancionados");
        jPanel1.add(lblSanc, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, 120, 30));

        lblTtlDe.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTtlDe.setForeground(new java.awt.Color(255, 255, 255));
        lblTtlDe.setText("Total de");
        jPanel1.add(lblTtlDe, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 80, 30));

        lblTtlLibros.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblTtlLibros.setForeground(new java.awt.Color(255, 255, 255));
        lblTtlLibros.setText("Total de Libros");
        jPanel1.add(lblTtlLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 180, 140, 30));

        lblDisp.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        lblDisp.setForeground(new java.awt.Color(255, 255, 255));
        lblDisp.setText("Disponibles");
        jPanel1.add(lblDisp, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 210, -1, -1));

        numTotalLib.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        numTotalLib.setForeground(new java.awt.Color(255, 255, 255));
        numTotalLib.setText("0");
        numTotalLib.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numTotalLibMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numTotalLibMouseExited(evt);
            }
        });
        jPanel1.add(numTotalLib, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 240, -1, -1));

        numTotalPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        numTotalPrest.setForeground(new java.awt.Color(255, 255, 255));
        numTotalPrest.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        numTotalPrest.setText("0");
        numTotalPrest.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        numTotalPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numTotalPrestMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numTotalPrestMouseExited(evt);
            }
        });
        jPanel1.add(numTotalPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 240, -1, -1));

        numTotalSan.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        numTotalSan.setForeground(new java.awt.Color(255, 255, 255));
        numTotalSan.setText("0");
        numTotalSan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                numTotalSanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                numTotalSanMouseExited(evt);
            }
        });
        jPanel1.add(numTotalSan, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 240, -1, -1));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TargClara.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, -1, 160));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TargClara.png"))); // NOI18N
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, 160));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/TargClara.png"))); // NOI18N
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, 160));

        lblBienvenido.setFont(new java.awt.Font("Kristen ITC", 1, 36)); // NOI18N
        lblBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        lblBienvenido.setText("Bienvenido!");
        jPanel1.add(lblBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, 240, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1038, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btn_principalMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMouseEntered
        btn_principal.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_principalMouseEntered

    private void btn_principalMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_principalMouseExited
        btn_principal.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_principalMouseExited

    private void btn_usuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuarioMouseEntered
        btn_usuario.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_usuarioMouseEntered

    private void btn_usuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuarioMouseExited
        btn_usuario.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_usuarioMouseExited

    private void btn_biblioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_biblioMouseEntered
        btn_biblio.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_biblioMouseEntered

    private void btn_biblioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_biblioMouseExited
        btn_biblio.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_biblioMouseExited

    private void btn_librosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_librosMouseEntered
        btn_libros.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_librosMouseEntered

    private void btn_librosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_librosMouseExited
        btn_libros.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_librosMouseExited

    private void btn_ejemplarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ejemplarMouseEntered
        btn_ejemplar.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_ejemplarMouseEntered

    private void btn_ejemplarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ejemplarMouseExited
        btn_ejemplar.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_ejemplarMouseExited

    private void btn_prestamoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseEntered
        btn_prestamo.setBackground(Color.decode("#0a9aa0"));
    }//GEN-LAST:event_btn_prestamoMouseEntered

    private void btn_prestamoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseExited
        btn_prestamo.setBackground(Color.decode("#0d6874"));
    }//GEN-LAST:event_btn_prestamoMouseExited

    private void numTotalPrestMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTotalPrestMouseEntered
        numTotalPrest.setFont(numTotalPrest.getFont().deriveFont(numTotalPrest.getFont().getSize() + 10.0f));
    }//GEN-LAST:event_numTotalPrestMouseEntered

    private void numTotalPrestMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTotalPrestMouseExited
        numTotalPrest.setFont(numTotalPrest.getFont().deriveFont(numTotalPrest.getFont().getSize() - 10.0f));
    }//GEN-LAST:event_numTotalPrestMouseExited

    private void numTotalSanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTotalSanMouseEntered
        numTotalSan.setFont(numTotalSan.getFont().deriveFont(numTotalSan.getFont().getSize() + 10.0f));
    }//GEN-LAST:event_numTotalSanMouseEntered

    private void numTotalSanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTotalSanMouseExited
        numTotalSan.setFont(numTotalSan.getFont().deriveFont(numTotalSan.getFont().getSize() - 10.0f));
    }//GEN-LAST:event_numTotalSanMouseExited

    private void numTotalLibMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTotalLibMouseEntered
        numTotalLib.setFont(numTotalLib.getFont().deriveFont(numTotalLib.getFont().getSize() + 10.0f));
    }//GEN-LAST:event_numTotalLibMouseEntered

    private void numTotalLibMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_numTotalLibMouseExited
        numTotalLib.setFont(numTotalLib.getFont().deriveFont(numTotalLib.getFont().getSize() - 10.0f));
    }//GEN-LAST:event_numTotalLibMouseExited

    private void lblCerrarSesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarSesMouseClicked
        Vista_inicioSesion vistaInicioS = new Vista_inicioSesion();
        InicioSesion inicioSesion = new InicioSesion();
        CrudInicioSesion crudInicioSesion = new CrudInicioSesion();
        Vista_principal vistaPrincipal = new Vista_principal();
        
        CtrlInicioSesion controlInicioSesion = new CtrlInicioSesion(vistaInicioS, inicioSesion,crudInicioSesion,vistaPrincipal);
        controlInicioSesion.iniciar();
        
        vistaInicioS.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblCerrarSesMouseClicked

    private void btn_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuarioMouseClicked
        Vista_gestionUsuario vistaU = new Vista_gestionUsuario();
        Usuario usuario = new Usuario();
        CrudUsuario consultasU = new CrudUsuario();
        
        CtrlUsuario controlU = new CtrlUsuario(vistaU,usuario, consultasU); 
        controlU.iniciar();
        
        vistaU.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_usuarioMouseClicked

    
    
    private void btn_biblioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_biblioMouseClicked
        Biblioteca mod = new Biblioteca();
        CrudBiblioteca modCrud = new CrudBiblioteca();
        Vista_gestionBiblioteca vis = new Vista_gestionBiblioteca();
        
        CtrlBiblioteca ctrl = new CtrlBiblioteca(mod, modCrud, vis);
        ctrl.iniciar();
        vis.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_biblioMouseClicked

    private void btn_librosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_librosMouseClicked
        Libro modL = new Libro();
        CrudLibro modCrudL = new CrudLibro();
        Vista_gestionLibros visL = new Vista_gestionLibros();

        CtrlLibro ctrlL = new CtrlLibro(modL, modCrudL, visL);
        ctrlL.iniciar();
        visL.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_librosMouseClicked

    private void btn_ejemplarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_ejemplarMouseClicked
        Ejemplar modE = new Ejemplar();
        CrudEjemplar modCrudE = new CrudEjemplar();
        Vista_gestionEjemplar visE = new Vista_gestionEjemplar();
        
        CtrlEjemplar ctrlE = new CtrlEjemplar(modE, modCrudE, visE);
        ctrlE.iniciar();
        visE.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_ejemplarMouseClicked

    private void btn_prestamoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_prestamoMouseClicked
        Prestamo modP = new Prestamo();
        CrudPrestamo modCP = new CrudPrestamo();
        Vista_gestionPrestamo vistaPres = new Vista_gestionPrestamo();
        
        CtrlPrestamo ctrlPres = new CtrlPrestamo(modP,modCP,vistaPres);
        ctrlPres.iniciar();
        vistaPres.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_prestamoMouseClicked

    
    
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        FlatMaterialLighterIJTheme.setup();
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PanelMenu;
    private javax.swing.JLabel PanelSup;
    private javax.swing.JLabel btnCerrar;
    public javax.swing.JPanel btn_biblio;
    public javax.swing.JPanel btn_ejemplar;
    public javax.swing.JPanel btn_libros;
    public javax.swing.JPanel btn_prestamo;
    public javax.swing.JPanel btn_principal;
    public javax.swing.JPanel btn_usuario;
    private javax.swing.JLabel imgLogoUsu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBiblio;
    private javax.swing.JLabel lblBienvenido;
    private javax.swing.JLabel lblCerrarSes;
    private javax.swing.JLabel lblDisp;
    private javax.swing.JLabel lblEjemplar;
    private javax.swing.JLabel lblLibros;
    private javax.swing.JLabel lblPrestamo;
    private javax.swing.JLabel lblPrincipalVista;
    private javax.swing.JLabel lblSanc;
    private javax.swing.JLabel lblTtlDe;
    private javax.swing.JLabel lblTtlLibros;
    private javax.swing.JLabel lblTtlPrest;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel logoBiblio;
    private javax.swing.JLabel numTotalLib;
    private javax.swing.JLabel numTotalPrest;
    private javax.swing.JLabel numTotalSan;
    // End of variables declaration//GEN-END:variables
}
