/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author HP
 */
public class Vista_emergenteRenovacion extends javax.swing.JFrame {

    /**
     * Creates new form Vista_emergenteRenovacion
     */
    public Vista_emergenteRenovacion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblRenovacion = new javax.swing.JLabel();
        lblIdRenovPrest = new javax.swing.JLabel();
        lblIdPrestamoPrest = new javax.swing.JLabel();
        txtIdRenovPrest = new javax.swing.JTextField();
        txtIdPrestamoPrest = new javax.swing.JTextField();
        btnRegistrarRenPrest = new javax.swing.JButton();
        btnModificarRenPrest = new javax.swing.JButton();
        btnEliminarRenPrest = new javax.swing.JButton();
        btnLimpiarRenPrest = new javax.swing.JButton();
        btnBuscarIdRenPrest = new javax.swing.JButton();
        btnBuscarIdPrest = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRenovPrest = new javax.swing.JTable();
        btnRegresarPrest = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        btnCerrar.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar.setText("X");
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 10, -1, -1));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        lblRenovacion.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lblRenovacion.setForeground(new java.awt.Color(255, 255, 255));
        lblRenovacion.setText("Renovación");

        lblIdRenovPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdRenovPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblIdRenovPrest.setText("Id Renovación:");

        lblIdPrestamoPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lblIdPrestamoPrest.setForeground(new java.awt.Color(255, 255, 255));
        lblIdPrestamoPrest.setText("Id Prestamo:");

        txtIdRenovPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtIdRenovPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdRenovPrest.setForeground(new java.awt.Color(0, 0, 0));
        txtIdRenovPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtIdPrestamoPrest.setBackground(new java.awt.Color(204, 204, 204));
        txtIdPrestamoPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        txtIdPrestamoPrest.setForeground(new java.awt.Color(0, 0, 0));
        txtIdPrestamoPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnRegistrarRenPrest.setBackground(new java.awt.Color(153, 153, 255));
        btnRegistrarRenPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnRegistrarRenPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrarRenPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-registro-20.png"))); // NOI18N
        btnRegistrarRenPrest.setText("Registrar");
        btnRegistrarRenPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRegistrarRenPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnModificarRenPrest.setBackground(new java.awt.Color(255, 102, 153));
        btnModificarRenPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnModificarRenPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarRenPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-modificar.png"))); // NOI18N
        btnModificarRenPrest.setText("Modificar");
        btnModificarRenPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnModificarRenPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEliminarRenPrest.setBackground(new java.awt.Color(153, 0, 0));
        btnEliminarRenPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnEliminarRenPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarRenPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-eliminar-20.png"))); // NOI18N
        btnEliminarRenPrest.setText("Eliminar");
        btnEliminarRenPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnEliminarRenPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnLimpiarRenPrest.setBackground(new java.awt.Color(51, 255, 102));
        btnLimpiarRenPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnLimpiarRenPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnLimpiarRenPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-limpiar-20.png"))); // NOI18N
        btnLimpiarRenPrest.setText("Limpiar");
        btnLimpiarRenPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLimpiarRenPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBuscarIdRenPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarIdRenPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarIdRenPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarIdRenPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarIdRenPrest.setText("Buscar");
        btnBuscarIdRenPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarIdRenPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnBuscarIdPrest.setBackground(new java.awt.Color(0, 204, 255));
        btnBuscarIdPrest.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        btnBuscarIdPrest.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarIdPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-búsqueda-15.png"))); // NOI18N
        btnBuscarIdPrest.setText("Buscar");
        btnBuscarIdPrest.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnBuscarIdPrest.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        tblRenovPrest.setBackground(new java.awt.Color(51, 51, 51));
        tblRenovPrest.setForeground(new java.awt.Color(255, 255, 255));
        tblRenovPrest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Id Multa", "Id Prestamo", "Fecha de Inicio", "Fecha de Vencimiento", "Id Estado Renovación", "Nombre de Renovación"
            }
        ));
        tblRenovPrest.setSelectionBackground(new java.awt.Color(13, 104, 116));
        jScrollPane1.setViewportView(tblRenovPrest);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblRenovacion))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblIdRenovPrest)
                .addGap(51, 51, 51)
                .addComponent(txtIdRenovPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnBuscarIdRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblIdPrestamoPrest)
                .addGap(65, 65, 65)
                .addComponent(txtIdPrestamoPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(btnBuscarIdPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(btnRegistrarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnModificarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnEliminarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLimpiarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRenovacion)
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdRenovPrest)
                    .addComponent(txtIdRenovPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdRenPrest))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdPrestamoPrest)
                    .addComponent(txtIdPrestamoPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarIdPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegistrarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpiarRenPrest, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 810, 460));

        btnRegresarPrest.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-atrás.png"))); // NOI18N
        btnRegresarPrest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarPrestMouseClicked(evt);
            }
        });
        jPanel1.add(btnRegresarPrest, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 30, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoEmerg.jpeg"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        System.exit(0);
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnRegresarPrestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarPrestMouseClicked
        Vista_gestionPrestamo vp = new Vista_gestionPrestamo();
        vp.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnRegresarPrestMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista_emergenteRenovacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista_emergenteRenovacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista_emergenteRenovacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista_emergenteRenovacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista_emergenteRenovacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarIdPrest;
    private javax.swing.JButton btnBuscarIdRenPrest;
    private javax.swing.JLabel btnCerrar;
    private javax.swing.JButton btnEliminarRenPrest;
    private javax.swing.JButton btnLimpiarRenPrest;
    private javax.swing.JButton btnModificarRenPrest;
    private javax.swing.JButton btnRegistrarRenPrest;
    private javax.swing.JLabel btnRegresarPrest;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdPrestamoPrest;
    private javax.swing.JLabel lblIdRenovPrest;
    private javax.swing.JLabel lblRenovacion;
    private javax.swing.JTable tblRenovPrest;
    private javax.swing.JTextField txtIdPrestamoPrest;
    private javax.swing.JTextField txtIdRenovPrest;
    // End of variables declaration//GEN-END:variables
}
